# Generated by Django 4.0.2 on 2022-02-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animal.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('local', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('doador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
                ('especie', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='animal.especie')),
                ('raca', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='animal.raca')),
            ],
        ),
    ]
