# Generated by Django 4.0.2 on 2022-02-13 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('animal', '0002_alter_animal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='animal.especie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='animal.raca'),
        ),
    ]
